//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelRentalBooking.SysModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBooking
    {
        public long IdBooking { get; set; }
        public Nullable<long> IdCustomer { get; set; }
        public Nullable<System.DateTime> DateCheckin { get; set; }
        public string RoomType { get; set; }
        public Nullable<bool> IsApproved { get; set; }
    }
}
